Update setup_database.py
```
E:\Coding\pennic-main>pipenv run setup_database

Loading .env environment variables...
Traceback (most recent call last):
  File "E:\Coding\pennic-main\pennic\setup_database.py", line 4, in <module>
    chain = Blockchain()
TypeError: Blockchain.__init__() missing 1 required positional argument: 'database_path'
```